#.github/workflows/php.yml
name: Library tests on PHP/MySQL
on:
  push: ~
  pull_request:
    branches: [ dev, main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.0' ]
        database: ['5.7', '8.0']
    name: PHP${{ matrix.php }}/MySQL${{ matrix.database }}
    services:
      mysql:
        image: mysql:${{ matrix.database }}
        env:
          MYSQL_DATABASE: main
          MYSQL_USER: main
          MYSQL_PASSWORD: main
          MYSQL_ROOT_PASSWORD: main
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@master
      - name: Validate composer.json
        run: composer validate --strict
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Echo PHP version
        run: php -v
      - name: Echo MySQL version
        run: mysql --user=root --password=main -h127.0.0.1 -e 'SELECT version()'

      - name: Copy testsuites
        run: cp phpunit.mysql${{ matrix.database }}.xml.dist phpunit.${{ matrix.database }}.xml
      - name: Install libraries
        run: composer update -vvv
      - name: Run test suite PHP${{ matrix.php }}/${{ matrix.database }}
        run: composer run-script test-mysql${{ matrix.database }}
